{
    'name': 'Real Estate',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Manage real estate listings',
    'description': "An awesome module for real estate properties.",
    'depends': ['base'],
    'data': ['security/ir.model.access.csv',
    'views/estate_property_views.xml',
    'views/estate_property_type_views.xml',
    'views/estate_property_tag.xml',
    'views/estate_property_offer.xml',
    'views/res_users_view.xml',
    'reports/estate_property_template.xml',
    'reports/estate_property_report.xml',
    'views/estate_menus.xml',],
    'installable': True,
    'application': True,  
    'auto_install': False,
}
